### ISSUE TITLE
[BUG] Unable to Run tvm project init

### ISSUE THREAD

**Issue by uetuluk** [eduNEXT/tvm#25] opened 2022-05-23 09:22 UTC
**Describe the bug**
I am trying to run the `tvm project init` command in another location after running it in one location.

I am also using virtualenv in both locations.

I encounter the following error after running the `tvm project init` command.
```bash
Traceback (most recent call last):
  File "/Users/uetuluk/.pyenv/versions/tutor-test-maple-tvm/bin/tvm", line 33, in <module>
    sys.exit(load_entry_point('tutor-version-manager==1.0.0', 'console_scripts', 'tvm')())
  File "/Users/uetuluk/.pyenv/versions/3.8.12/envs/tutor-test-maple-tvm/lib/python3.8/site-packages/tvm/cli.py", line 32, in main
    cli()
  File "/Users/uetuluk/.pyenv/versions/3.8.12/envs/tutor-test-maple-tvm/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/uetuluk/.pyenv/versions/3.8.12/envs/tutor-test-maple-tvm/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/uetuluk/.pyenv/versions/3.8.12/envs/tutor-test-maple-tvm/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/uetuluk/.pyenv/versions/3.8.12/envs/tutor-test-maple-tvm/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/uetuluk/.pyenv/versions/3.8.12/envs/tutor-test-maple-tvm/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/uetuluk/.pyenv/versions/3.8.12/envs/tutor-test-maple-tvm/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/uetuluk/.pyenv/versions/3.8.12/envs/tutor-test-maple-tvm/lib/python3.8/site-packages/tvm/cli.py", line 429, in init
    if not version_is_installed(version):
  File "/Users/uetuluk/.pyenv/versions/3.8.12/envs/tutor-test-maple-tvm/lib/python3.8/site-packages/tvm/cli.py", line 79, in version_is_installed
    version_is_valid(value)
  File "/Users/uetuluk/.pyenv/versions/3.8.12/envs/tutor-test-maple-tvm/lib/python3.8/site-packages/tvm/cli.py", line 58, in version_is_valid
    result = re.match(r'^v([0-9]+)\.([0-9]+)\.([0-9]+)$', value)
  File "/Users/uetuluk/.pyenv/versions/3.8.12/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

**To Reproduce**
1. Create virtualenv A in location A 
2. Install tvm inside virtualenv A
3. Run `tvm install v13.2.2`
4. Run `tvm project init`
A method

5. Use virtualenv A in location B
6. Run `tvm project init`

or B method
5. Run `tvm project init` again

**Desktop (please complete the following information):**
 - TVM Version: 1.0.0
 - Python: 3.8.12
 - Tutor: 13.2.2

**Solution**
I found that running `tvm use v13.2.2` fixes this issue.
However, the `tvm list` looks like this.

v13.2.2@yEZdugrjET
v13.2.2 (active)
...

**Comment by Alec4r** [comment] 2022-05-23 12:03
Hi @uetuluk 😄, thanks for reporting it, We will check what is happening with this, we have never done hard tests using TVM inside virtualenv because TVM was designed to be used globally as a tool, but We will discuss and check it.

Thanks.

**Comment by MaferMazu** [comment] 2022-10-12 20:22
Hi @uetuluk, We launched TVM 2.1.0 with [its documentation](https://tvm.docs.edunext.co/en/latest/). I will close this issue, but if you still have problems with TVM, please let us know in another issue.

**Closed by MaferMazu** 2022-10-12 20:22 UTC
Labels: bug, help wanted
